server:
  port: 9168
springdoc:
  swagger-ui:
    path: /swagger-ui.html
graceful-response:
  print-exception-in-global-advice: true
  default-error-msg: fail
  default-error-code: 500
  default-success-code: 200
  default-success-msg: success
  response-style: 1
  exclude-packages:
    - com.feiniaojin.*.controller.exclude
    - springfox.**
  # response-class-full-name: com.feiniaojin.gracefuresponse.example.config.CustomResponseImpl
  origin-exception-using-detail-message: false
  default-validate-error-code: 999
  exclude-urls:
    - /**/ex/**
    - /**/api-docs/**
    - /**/error/**
  i18n: true
  exclude-return-types:
    - com.feiniaojin.gracefuresponse.example.dto.Result
  exclude-exception-types:
    - com.feiniaojin.gracefuresponse.example.exceptions.ExcludeException
  exclude-exception-packages:
    - "*excludep*"
  exception-alias-config-map:
    "[com.feiniaojin.gracefuresponse.example.exceptions.outer.OuterException]":
        code: 5200
        httpStatusCode: 401
        msg: "提示信息"

#  json-http-message-converter: com.alibaba.fastjson2.support.spring6.http.converter.FastJsonHttpMessageConverter
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: "*.html"
    add-mappings: false
    view:
      suffix: .html
      prefix: /
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com.feiniaojin: DEBUG

knife4j:
  enable: true
  setting:
    language: zh_cn
